experiment:
  name: ResNet_GradCAM_v1
  log_dir: <path/to/log_dir>
  neptune_config_file: CNN/configs/common/neptune_configs.yaml 
  seed: 2024
  early_stop:
    name: EarlyStopping
    config:
      monitor: valid/loss
      patience: 3
      mode: min
  trainer:
    max_epochs: 100
    check_val_every_n_epoch: 1
    log_every_n_steps: 2
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    track_grad_norm: 2
  tags:
    - DLaTA