module:
  name: FrequencyClassifier
  config:
    model:
      name: ResNetTimeSeriesClassifier
      config:
        encoder_params:
          encoding_size: 24
          base_filters: 16
          kernel_size: 20
          stride: 1
          groups: 1
          n_block: 2
          downsample_gap: 1
          increasefilter_gap: 1
          use_batch_norm: True
          use_inner_do: False
          inner_do_val: 0. 
          use_final_do: True
          final_do_val: 0.2
          gradcam: False # True
        classifier_params:
          out_channels: 6
    loss:
      name: CrossEntropyLoss
    optimizer:
      name: Adam
      config: 
        lr: 0.001
    metrics:
      - name: Accuracy
        config:
          average: macro
          task: multiclass
          num_classes: 6
          multidim_average: global
      - name: Precision
        config:
          average: macro
          task: multiclass
          num_classes: 6
          multidim_average: global
      - name: Recall
        config:
          average: macro
          task: multiclass
          num_classes: 6
          multidim_average: global
      - name: F1 
        config:
          average: macro
          task: multiclass
          num_classes: 6
          multidim_average: global